# Generated by Django 4.0.3 on 2022-03-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkubooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kkubookmode',
            name='kkubook_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kkubookmode',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kkubookmode',
            name='notcommit_days',
            field=models.IntegerField(default=0),
        ),
    ]
